baseURL = 'http://cruftex.net'
DefaultContentLanguage = "en"
languageCode = 'en-us'
title = 'cruftex.net'
theme = 'diary'
uglyURLs = true

# Pagination configuration
[pagination]
  pagerSize = 10

# Site parameters
[params]
  subtitle = "Java caching and performance"
  description = "Personal blog of Jens Wilke"
  author = "Jens Wilke"
  enableOpenGraph = true
  enableTwitterCards = true

# Permalinks configuration
[permalinks]
  posts = '/:year/:month/:day/:title'

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    style = 'github'
    noClasses = false

# Menu configuration
[[menu.main]]
  url = "/posts.html"
  name = "Archive"
  weight = 1
[[menu.main]]
  url = "/tags.html"
  name = "Tags"
  weight = 2
[[menu.main]]
  url = "/about.html"
  name = "About"
  weight = 3

# RSS/Atom feed
[outputs]
  home = ['HTML', 'RSS']
  
[outputFormats]
  [outputFormats.RSS]
    mediatype = 'application/rss+xml'
    baseName = 'atom'
